# Generated by Django 1.9.2 on 2016-02-05 17:27
from django.apps import apps
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('two_factor', '0003_auto_20150817_1733'),
    ]

    if apps.is_installed('two_factor.plugins.phonenumber'):
        import phonenumber_field.modelfields

        operations = [
            migrations.AlterField(
                model_name='phonedevice',
                name='number',
                field=phonenumber_field.modelfields.PhoneNumberField(max_length=128),
            ),
        ]
    else:
        operations = []
