# Generated by Django 2.0.3 on 2018-08-12 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('two_factor', '0005_auto_20160224_0450'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrustedAgent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_agent', models.CharField(blank=True, max_length=200)),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('phone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='two_factor.PhoneDevice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('yubi_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='trustedagent',
            unique_together={('user', 'user_agent')},
        ),
    ]
