# Generated by Django 3.2.4 on 2022-08-20 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('two_factor', '0007_auto_20201201_1019'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='PhoneDevice',
                ),
            ],
        ),
    ]
