# Generated by Django 3.1.5 on 2021-02-02 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('two_factor', '0008_webauthndevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='webauthndevice',
            name='throttling_failure_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of successive failed attempts.'),
        ),
        migrations.AddField(
            model_name='webauthndevice',
            name='throttling_failure_timestamp',
            field=models.DateTimeField(blank=True, default=None, help_text='A timestamp of the last failed verification attempt. Null if last attempt succeeded.', null=True),
        ),
    ]
