repos:
  - repo: https://github.com/PyCQA/isort
    rev: 9.0.0b1
    hooks:
    - id: isort
      args: ['--check-only', '--diff']

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.22
    hooks:
      - id: ruff
