build:
    os: ubuntu-lts-latest
    tools:
        python: "3.12"

sphinx:
    configuration: docs/conf.py

python:
    install:
        - method: pip
          path: .
          extra_requirements:
            - docs
