[tox]
envlist =
    py{311,312,313,314}-dj52-{normal,yubikey,custom_user,webauthn}
    py{312,313,314}-{dj60,main}-{normal,yubikey,custom_user,webauthn}

[gh-actions]
python =
    3.11: py311
    3.12: py312
    3.13: py313
    3.14: py314

[gh-actions:env]
DJANGO =
    5.2: dj52
    6.0: dj60
    main: djmain
VARIANT =
    normal: normal
    webauthn: webauthn
    yubikey: yubikey
    custom_user: custom_user

[testenv]
passenv =
    HOME
    DISPLAY
setenv =
    PYTHONDONTWRITEBYTECODE=1
    PYTHONWARNINGS=always
    custom_user: AUTH_USER_MODEL=tests.User
basepython =
    py311: python3.11
    py312: python3.12
    py313: python3.13
    py314: python3.14
deps =
    dj52: Django<5.3
    dj60: Django<6.0
    djmain: https://github.com/django/django/archive/main.tar.gz
    webauthn: -rrequirements_e2e.txt
extras =
    tests
    call
    phonenumberslite
    yubikey: yubikey
    webauthn: webauthn
ignore_outcome =
    djmain: True
commands =
    coverage run {env:COVERAGE_OPTIONS:} {envbindir}/django-admin test -v 2 --pythonpath=./ --settings=tests.settings
    coverage report

[testenv:ruff]
basepython = python3
extras = linting
commands = ruff check .

[testenv:isort]
basepython = python3
extras = linting
commands = isort -c --diff example tests two_factor

[testenv:docs]
allowlist_externals = make
changedir = docs
commands = make html
extras = docs
