# Generated by Django 4.2.1 on 2023-05-08 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonenumber', '0001_squashed_0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonedevice',
            name='data',
            field=models.JSONField(
                blank=True,
                null=True,
                default=dict,
                help_text='Additional data for phone device',
                verbose_name='Additional data for phone device'
            ),
        ),
    ]
