# Generated by Django 4.2.7 on 2023-11-02 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonenumber', '0001_squashed_0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonedevice',
            name='method',
            field=models.CharField(choices=[('call', 'Phone Call'), ('sms', 'Text Message'), ('wa', 'WhatsApp Message')], max_length=4, verbose_name='method'),
        ),
    ]
